import { getTodayLocalDateString } from "../utils/date-utils.js";


export const DEFAULT_DISPATCH_DATE = getTodayLocalDateString();
export const AUTH_ACCOUNT_NAME_SESSION_KEY = "manualDispatchAccountName";
export const AUTH_ACCOUNT_ID_SESSION_KEY = "manualDispatchAccountId";


export const state = {
  dispatchDate: DEFAULT_DISPATCH_DATE,
  driverSummaryDeliveryDate: DEFAULT_DISPATCH_DATE,
  accountName: "",
  accountId: "",
  isLoggedIn: false,
  authMode: "login",
  loginError: "",
  registerError: "",
  authSuccessMessage: "",
  resetError: "",
  isAuthLoading: false,
  isLoading: false,
  isSaving: false,
  errorMessage: "",
  orders: [],
  drivers: [],
  vehicles: [],
  assignments: [],
  driverVehicleAssignments: [],
  opshopPickups: [],
  assignedOpShopPickups: [],
  scheduledOpShopPickups: [],
  oncallOpShopPickups: [],
  opshopRegularListWindowStart: "",
  opshopRegularListWindowEnd: "",
  opshopPickupAssignedDriverSelections: {},
  oncallOpShopPickupAssignedDriverSelections: {},
  opshopPickupScheduleCandidates: [],
  oncallOpShopPickupScheduleCandidates: [],
  isOpShopPickupListOpen: false,
  isOncallOpShopPickupListOpen: false,
  isOpShopPickupListLoading: false,
  isOncallOpShopPickupListLoading: false,
  isOpShopPickupSaving: false,
  isOncallOpShopPickupSaving: false,
  opshopPickupListError: "",
  oncallOpShopPickupListError: "",
  opshopPickupFormMode: "",
  oncallOpShopPickupFormMode: "",
  opshopPickupEditingTaskId: "",
  oncallOpShopPickupEditingTaskId: "",
  opshopPickupForm: {},
  oncallOpShopPickupForm: {},
  pendingSelections: {},
  taskPoolSearch: "",
  urgencyFilter: "All",
  taskPoolDeliveryDateFilter: "",
  finalTripSummaries: {},
  generatedTaskKeys: new Set(),
  isSavingFinalSummaries: false,
  finalSummaryGlobalSaveError: "",
  finalSummaryGlobalSaveSuccess: "",
  finalSummaryDates: [],
  historyDate: DEFAULT_DISPATCH_DATE,
  finalSummaryHistory: [],
  isHistoryLoading: false,
  historyLoaded: false,
  historyError: "",
  isSpecificationModalOpen: false,
  specificationDrivers: [],
  specificationVehicles: [],
  specificationError: "",
  specificationLoading: false,
  specificationSaving: false,
  specificationActiveTab: "drivers",
  specificationDirty: false,
  driverSpecificationForm: null,
  driverSpecificationEditingId: "",
  vehicleSpecificationForm: null,
  vehicleSpecificationEditingId: "",
  activeOrderDetailId: "",
  activeOpShopPickupDetailId: "",
  isProductDetailOpen: false,
  isAddOrderOpen: false,
  addOrderError: "",
  addOrderForm: {},
  isOrderEditMode: false,
  orderEditError: "",
  orderEditForm: {},
};
