import { getTodayLocalDateString } from "../utils/date-utils.js";


export const DEFAULT_DISPATCH_DATE = getTodayLocalDateString();
export const AUTH_ACCOUNT_NAME_SESSION_KEY = "manualDispatchAccountName";
export const AUTH_ACCOUNT_ID_SESSION_KEY = "manualDispatchAccountId";


export const state = {
  dispatchDate: DEFAULT_DISPATCH_DATE,
  accountName: "",
  accountId: "",
  isLoggedIn: false,
  authMode: "login",
  loginError: "",
  registerError: "",
  authSuccessMessage: "",
  resetError: "",
  isAuthLoading: false,
  isLoading: false,
  isSaving: false,
  errorMessage: "",
  orders: [],
  drivers: [],
  vehicles: [],
  assignments: [],
  driverVehicleAssignments: [],
  pendingSelections: {},
  taskPoolSearch: "",
  urgencyFilter: "All",
  finalTripSummaries: {},
  generatedTaskKeys: new Set(),
  isSavingFinalSummaries: false,
  finalSummaryGlobalSaveError: "",
  finalSummaryGlobalSaveSuccess: "",
  finalSummaryDates: [],
  historyDate: DEFAULT_DISPATCH_DATE,
  finalSummaryHistory: [],
  isHistoryLoading: false,
  historyLoaded: false,
  historyError: "",
  isSpecificationModalOpen: false,
  specificationDrivers: [],
  specificationVehicles: [],
  specificationError: "",
  specificationLoading: false,
  specificationSaving: false,
  specificationActiveTab: "drivers",
  specificationDirty: false,
  driverSpecificationForm: null,
  driverSpecificationEditingId: "",
  vehicleSpecificationForm: null,
  vehicleSpecificationEditingId: "",
  activeOrderDetailId: "",
  isAddOrderOpen: false,
  addOrderError: "",
  addOrderForm: {},
  isOrderEditMode: false,
  orderEditError: "",
  orderEditForm: {},
};
