"""Dev-only reset for Phase 14 Manual Dispatch Board demo Orders.

This script clears local runtime dispatch data and inserts 20 Victoria demo
Orders. It is intentionally manual and must not run during application startup.
Driver and Vehicle master data are retained.
"""

import sys
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parents[1]
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from backend.db.connection import connect, get_database_path, initialize_database


DEMO_ORDERS = [
    (
        "ORD-VIC-1001",
        "VIC-1001",
        "Melbourne Metro Supplies",
        "0390001001",
        "12 Market Street",
        "South Melbourne",
        "3205",
        "2026-05-05",
        "Inner South",
        "Normal",
        None,
        1,
        0,
        "08:00",
        "10:00",
        "Office delivery",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1002",
        "VIC-1002",
        "Dandenong Cleaning Co",
        "0390001002",
        "45 Cheltenham Road",
        "Dandenong",
        "3175",
        "2026-05-05",
        "South East",
        "Urgent",
        None,
        2,
        0,
        "08:30",
        "11:00",
        "Call before delivery",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1003",
        "VIC-1003",
        "Clayton Workshop Supplies",
        "0390001003",
        "8 Centre Road",
        "Clayton",
        "3168",
        "2026-05-05",
        "South East",
        "Normal",
        None,
        0,
        10,
        "09:00",
        "12:00",
        "Loose bags only",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1004",
        "VIC-1004",
        "Springvale Wholesale",
        "0390001004",
        "22 Springvale Road",
        "Springvale",
        "3171",
        "2026-05-05",
        "South East",
        "Normal",
        None,
        3,
        0,
        "09:00",
        "12:00",
        "Warehouse entry",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1005",
        "VIC-1005",
        "Moorabbin Trade Centre",
        "0390001005",
        "17 Keys Road",
        "Moorabbin",
        "3189",
        "2026-05-05",
        "South",
        "Normal",
        None,
        1,
        4,
        "10:00",
        "13:00",
        "Rear loading dock",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1006",
        "VIC-1006",
        "Braeside Industrial Group",
        "0390001006",
        "31 Industrial Drive",
        "Braeside",
        "3195",
        "2026-05-05",
        "South",
        "Urgent",
        None,
        2,
        0,
        "08:00",
        "10:30",
        "Forklift available",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1007",
        "VIC-1007",
        "Scoresby Facility Services",
        "0390001007",
        "6 Koornang Road",
        "Scoresby",
        "3179",
        "2026-05-05",
        "East",
        "Normal",
        None,
        2,
        2,
        "11:00",
        "14:00",
        "Delivery to reception",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1008",
        "VIC-1008",
        "Ringwood Commercial Laundry",
        "0390001008",
        "19 Maroondah Highway",
        "Ringwood",
        "3134",
        "2026-05-05",
        "East",
        "Normal",
        None,
        1,
        0,
        "12:00",
        "15:00",
        "None",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1009",
        "VIC-1009",
        "Truganina Distribution Hub",
        "0390001009",
        "55 Palmers Road",
        "Truganina",
        "3029",
        "2026-05-05",
        "West",
        "Urgent",
        None,
        4,
        0,
        "08:00",
        "11:00",
        "Large order",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1010",
        "VIC-1010",
        "Werribee Hospitality Supplies",
        "0390001010",
        "14 Watton Street",
        "Werribee",
        "3030",
        "2026-05-05",
        "West",
        "Normal",
        None,
        1,
        6,
        "10:00",
        "13:00",
        "Call site manager",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1011",
        "VIC-1011",
        "Sunshine Packaging Services",
        "0390001011",
        "88 Ballarat Road",
        "Sunshine",
        "3020",
        "2026-05-05",
        "West",
        "Normal",
        None,
        2,
        0,
        "09:30",
        "12:30",
        "Front office",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1012",
        "VIC-1012",
        "Tullamarine Airport Supplies",
        "0390001012",
        "7 Assembly Drive",
        "Tullamarine",
        "3043",
        "2026-05-05",
        "North West",
        "Urgent",
        None,
        3,
        0,
        "07:30",
        "10:00",
        "Security gate",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1013",
        "VIC-1013",
        "Epping Market Services",
        "0390001013",
        "25 Cooper Street",
        "Epping",
        "3076",
        "2026-05-05",
        "North",
        "Normal",
        None,
        2,
        0,
        "11:00",
        "14:00",
        "Market loading area",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1014",
        "VIC-1014",
        "Thomastown Maintenance Supplies",
        "0390001014",
        "40 Settlement Road",
        "Thomastown",
        "3074",
        "2026-05-05",
        "North",
        "Normal",
        None,
        0,
        12,
        "12:00",
        "15:00",
        "Loose bags only",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1015",
        "VIC-1015",
        "Campbellfield Manufacturing",
        "0390001015",
        "3 Sydney Road",
        "Campbellfield",
        "3061",
        "2026-05-05",
        "North",
        "Urgent",
        None,
        5,
        0,
        "08:00",
        "12:00",
        "Heavy pallet delivery",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1016",
        "VIC-1016",
        "Preston Retail Supplies",
        "0390001016",
        "76 High Street",
        "Preston",
        "3072",
        "2026-05-05",
        "Inner North",
        "Normal",
        None,
        1,
        2,
        "10:30",
        "13:30",
        "Shopfront delivery",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1017",
        "VIC-1017",
        "Richmond Venue Services",
        "0390001017",
        "29 Swan Street",
        "Richmond",
        "3121",
        "2026-05-05",
        "Inner East",
        "Normal",
        None,
        1,
        0,
        "09:00",
        "12:00",
        "Deliver before lunch",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1018",
        "VIC-1018",
        "Frankston Coastal Supplies",
        "0390001018",
        "61 Beach Street",
        "Frankston",
        "3199",
        "2026-05-05",
        "Bayside",
        "Normal",
        None,
        2,
        0,
        "11:00",
        "15:00",
        "Call on arrival",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1019",
        "VIC-1019",
        "Cranbourne Service Centre",
        "0390001019",
        "18 South Gippsland Highway",
        "Cranbourne",
        "3977",
        "2026-05-05",
        "South East",
        "Urgent",
        None,
        3,
        3,
        "08:30",
        "11:30",
        "Side driveway",
        "ACTIVE",
    ),
    (
        "ORD-VIC-1020",
        "VIC-1020",
        "Geelong Regional Supplies",
        "0390001020",
        "90 Moorabool Street",
        "Geelong",
        "3220",
        "2026-05-05",
        "Regional West",
        "Normal",
        None,
        4,
        0,
        "12:00",
        "16:00",
        "Regional delivery",
        "ACTIVE",
    ),
]


def main():
    db_path = get_database_path()
    initialize_database(db_path)

    with connect(db_path) as connection:
        driver_count = connection.execute("SELECT COUNT(*) FROM manual_drivers").fetchone()[0]
        vehicle_count = connection.execute("SELECT COUNT(*) FROM manual_vehicles").fetchone()[0]

        connection.execute("DELETE FROM final_trip_summary_rows")
        connection.execute("DELETE FROM final_trip_summaries")
        connection.execute("DELETE FROM manual_dispatch_assignments")
        connection.execute("DELETE FROM manual_driver_vehicle_assignments")
        connection.execute("DELETE FROM manual_orders")
        connection.executemany(
            """
            INSERT INTO manual_orders (
                order_id,
                invoice_number,
                company_name,
                phone,
                delivery_address,
                suburb,
                postcode,
                delivery_date,
                zone,
                urgency,
                preferred_driver_id,
                pallet_quantity,
                loose_bags_quantity,
                start_time,
                end_time,
                note,
                status
            ) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
            """,
            DEMO_ORDERS,
        )
        connection.commit()

    print(f"Database: {db_path}")
    print(f"Orders inserted: {len(DEMO_ORDERS)}")
    print("Assignments cleared")
    print("Driver vehicle selections cleared")
    print("Final summaries cleared")
    print(f"Drivers retained: {driver_count}")
    print(f"Vehicles retained: {vehicle_count}")


if __name__ == "__main__":
    main()
